site_name: 'Modelos de IA (CE Inteligencia Artificial y Big Data)'
site_url: https://martinezpenya.es/ModelosIA/
repo_url: https://github.com/martinezpenya/ModelosIA
edit_uri: edit/main/docs

nav:
  - UD00:
    - Información importante: index.md
  - Docker:
    - Introducción a docker: Docker/Docker.md
  - UD01:
    - Caracterización de sistemas y utilización de modelos de Inteligencia Artificial: UD01/UD01_ES.md
    - Diapositivas: UD01/diapositivas.md
    - Actividades:
      - P01 Robocode: UD01/UD01_P01_RobocodeTankRoyale_ES.md
      - P02 Entregable: UD01/UD01_P02_Practica_ES.md
    - Talleres:
      - T01 Java: UD01/UD01_T01_IDE_ES.md
      - T02 GitHub: UD01/UD01_T02_GitHub.md
      - T03 Markdown: UD01/UD01_T03_Markdown.md
  - UD02:
    - Sistemas basados en el conocimiento: UD02/UD02_ES.md
    - Diapositivas: UD02/UD02_Diapositivas.md
    - Actividades Guiadas: UD02/UD02_ActividadesGuiadas.md
    - Actividades Entregables: UD02/UD02_ActividadesEntregables.md
  - UD03:
    - Procesamiento del Lenguaje Natural: UD03/UD03_ES.md
    - Diapositivas: UD03/UD03_Diapositivas.md
    - Actividades Guiadas: UD03/UD03_ActividadesGuiadas.md
    - Actividades Entregables: UD03/UD03_ActividadesEntregables.md
  - UD04:
    - Análisis de sistemas robotizados: UD04/UD04_ES.md
    #- Diapositivas: UD04/UD04_Diapositivas.md
    - Actividades Guiadas: UD04/UD04_ActividadesGuiadas.md
    - Actividades Entregables: UD04/UD04_ActividadesEntregables.md
  - UD05:
    - Aplicación de principios legales y éticos de la IA: UD05/UD05_ES.md
    #- Diapositivas: UD05/UD05_Diapositivas.md
    - Actividades Guiadas: UD05/UD05_ActividadesGuiadas.md
    - Actividades Entregables: UD05/UD05_ActividadesEntregables.md
  - Sobre mi: sobremi.md
  - Fuentes de información: fuentes.md

theme:
  name: material
  language: es
  features:
    - header.autohide
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.anotate
    #- content.tabs.link
    - toc.follow
    - toc.integrate
    - navigation.top
    #- navigation.tracking
    - navigation.footer
    #- navigation.indexes
  icon:
    logo: material/robot-confused-outline
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/hexagon-nodes
      quote: fontawesome/solid/quote-left
  favicon: assets/favicon.ico
#  features:
#    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: lime
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      #anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex
extra_javascript:
  - js/mathjax-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js
extra:
  search:
    language: es
  social:
    - icon: simple/youtube
      link: https://youtube.com/@martinezpenya
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/martinezpenya
    - icon: fontawesome/brands/github
      link: https://github.com/martinezpenya
    - icon: fontawesome/solid/mug-saucer
      link: https://buymeacoffee.com/martinezpenya
      name: Buy me a coffee
#  consent:
#    title: Consentimiento de cookie
#    description: >-
#      Esta página de apuntes utiliza cookies para reconocer las visitas, medir la #efectividad de la documentación
#      y averiguar si encuentras aquello que buscas o cómo has llegado a estos apuntes.
#      Con tu consentimiento, me ayudas a mejorar estos materiales.

copyright: "© 2025 David Martínez licensed under CC BY-NC-SA 4.0"

plugins:
    - mkdocs-video
    - offline
    - search
    - git-revision-date-localized:
        fallback_to_build_date: true
    - minify:
        minify_html: true
    - extra-sass
    - with-pdf:
        author: David Martinez Peña
        #copyright: (www.martinezpenya.es)
        #
        cover: true
        #cover_logo: docs/assets/images/aws_cast.png
        cover_logo: https://martinezpenya.es/ModelosIA/assets/portada.png
        back_cover: true
        #cover_title: TITLE TEXT
        cover_subtitle: IES Eduardo Primo Marques (Carlet)
        #custom_template_path: templates
        #
        toc_title: Indice de contenidos
        #heading_shift: false
        toc_level: 3
        ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: docs/Libro.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        # show_anchors: true
        # verbose: true
